# -*- coding: utf-8 -*-
"""LVADSUSR169_final_assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i239PrLjVdOOjIHPlsRK9V2Bcv6im58P
"""

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
plt.style.use('fivethirtyeight')

#1a
df = pd.read_csv('/content/sample_data/Final Dataset - IPL.csv')

#1b
df.describe()

#1b
df.isnull().sum()

#1b
df.dtypes

#2a
df.isnull().sum()
#there are no null values to handle or drop they are completly reliable for futher analysis

#2b
'''
there are all unique values in the columns which has no duplicate in the dataset
'''
df.nunique()

#3
'''
the pandas gives the discriptive analysis of the dataset between various parameters
and all the numerical columns
'''
df.describe()

#4
'''
by using this scatter plot there we finf that there is a linear relationship between
 first_ings_score and second_ings_score
 '''
the_count_match_winner_by_toss = df[df['toss_winner'] == df['match_winner']].value_counts()
df.plot(x = 'first_ings_score',y = 'second_ings_score',kind = "scatter")

#4
'''
by seeing this we can say that the team banglore is the most winning team in the ipl
'''
df.groupby('team1')['match_winner'].value_counts().sort_values().tail(15).plot(kind = 'bar')

#4
'''
the player quinton de knock is the top player with the highest score among the top players
'''
df.sort_values(by = 'highscore',ascending = True).tail(10).plot(x = 'top_scorer',y = 'highscore', kind = 'barh')

#4
'''
the peple are mostly choosing feilding in or der to get chase the kept target
'''
df['toss_decision'].value_counts().plot(kind = 'pie',autopct = '%1.f%%')

#4
'''
using heat map we can say the relation ship between the columns
'''
df1 = df[['first_ings_score','first_ings_wkts' ]].head(10)
sns.heatmap(data = df1, cmap = 'viridis',annot = True)

#4
print( df.groupby(['stage'])['first_ings_score'].max().sort_values(ascending = False))
df.groupby(['stage'])['first_ings_score'].max().plot(kind = 'pie',autopct = '%1.f%%')
'''
the maximum score in the stage of group only because the compitency of the teams is different
coming on the levels increases the toughness increses hence the maximum score also reduced
'''

print(df.groupby('team1')['match_winner'].count())
df.groupby('team1')['match_winner'].count().sort_values(ascending = False).plot(kind = 'bar')
'''
team banglore won more matches compared to all teams
'''

#5
df.groupby(['team1','toss_decision'])['match_winner'].value_counts().sort_values(ascending = False).head(5)
'''
here we get to know that the field toss decision makes the winning chances higher and
the team banglore is succeded in that and it won the 7 matches by choosing the fielding as the toss_decision
'''

#5
first_inngs_winners = df.groupby('match_winner')['first_ings_score'].mean().sort_values(ascending = False).head(2)
second_inngs_winners = df.groupby('match_winner')['second_ings_score'].mean().sort_values(ascending = False).head(2)
first_inngs_winners,second_inngs_winners
'''
here we can observe the winng scre of the first_innings_score is far
greater than the second innings score hence the maximum score recorded in the ipl is came from the first innings
'''

#5
df.groupby(['venue','toss_decision'])['match_winner'].value_counts().sort_values(ascending = False).head(10)
'''
 By this we cn understand that the sadium ground is favorable for batting or bowling the Brabourne Stadium, Mumbai
  is only the stadium in which the batting is more chances to wi remaing all the fielding n=means the ground is favorable for boling rather than bating
  '''

#6
df.plot(kind = 'box')
'''
the box plot helps in the finding outliers
we can see that there are so many anomolies or outliers in column of margin we need to take care
 while analysis we can handle them by substituting the mean or median values accoding to use of the column
the outliers in the column margin can be handled by removing the column because the dataset is towards the whole ipl if it is specific to one team the
we can check that at what margin the team is loosing the game and resoective actions can be taken by the team
 '''

#7
first_inngs_winners_by_venue = df.groupby('venue')['first_ings_score'].mean().head(3)
second_inngs_winners_by_venue= df.groupby('venue')['second_ings_score'].mean().head(3)
second_inngs_winners_by_venue,first_inngs_winners_by_venue
'''
by the outcome we can analuyze that the stadium namely DY Patil Sports Academy, Mumbai is the bowling stadium in which the match winner scred more score
second inngs means the bowiling playes a key role and they can get more runs in than batting
'''

#8
df.groupby('best_bowling')['won_by'].value_counts().sort_values(ascending = False).head(10)
'''
the best bowler contains in the team amount of contribution for the team winning for the 1st person is less
 because won by runs which has more preference to the batsman compared to the bowler
 '''
df.groupby('top_scorer')['won_by'].value_counts().sort_values(ascending = False).head(10)
'''
the batsman has the more contribution towards winning the match the match won by the runs due the runs scored by the top
performer in the match hence the contributuion od the top performer is mor more on the matches
'''

#9
'''
by the whole process of analysis of the ipl dataset that there are some insights drawn
-> there is a lot of correlation between the toss_decision and the match winng through out the analysis the team which cgoose to field in the toss
got succeded when compared to bat
-> there is more contribution of the top_scorer in the winning the match when compared to the best_bolwer
-> there is a linear relation ship between the first_innings_score and second
-> the outliers in the column margin can be handled by removing the column because the dataset is towards the whole ipl if it is specific to one team the
we can check that at what margin the team is loosing the game and resoective actions can be taken by the team
-> the venue effects the most on the winning chances because the atmospheric change the ball can accordingly acts hence the venue also shown so much of the
effect on the match winning
-> the toss decision feilding is choosen the most anthe matches which choose the feld only won mostly
->team banglore won more matches compared to all teams
'''



















